name: Lunaria
main: lunaria.Main
description: Custom plugin for the Lunaria Server
version: 7.3.15
author: qsik

commands:
  funitems:
  usa:
  party:
  cake:
  cookout:
  
permissions:
  funitems:
    default: true
  bypasstp:
    default: false