name: Lunaria
main: lunaria.Main
description: Custom plugin for the Lunaria Server
version: 7.3.15
author: qsik
depend: [Vault]

commands:
  lunaria:
    permission: ladmin
  votepay:
  funitems:
  cake:
  usa:
    permission: usa
  cookout:
    permission: usa
  party:
    permission: usa
permissions:
  funitems:
    default: true
  bypasstp:
    default: false